// Generated by AI Architect
// Handles .m3u playlist export/import functionality

import Foundation
import SwiftUI
import MediaLibraryBuilder // Import the Objective-C module

class PlaylistExporter {
    // MARK: - Export Workflow
    /// Exports a playlist as a .m3u file with optional sidecar image
    /// - Parameters:
    ///   - toFileURL: Destination URL for the .m3u file
    ///   - playlistName: Name of the playlist (used for filename and sidecar)
    ///   - songs: Array of SongMetadata to export
    /// - Throws: Various errors if validation fails or write operations fail
    func exportPlaylist(toFileURL: URL, playlistName: String, songs: [SongMetadata]) throws {
        // 1. Validate inputs
        guard !playlistName.isEmpty, !songs.isEmpty else {
            throw PlaylistExporterError.invalidInput
        }
        
        // 2. Generate .m3u content with proper EXTINF lines
        let m3uContent = generateM3UContent(songs: songs)
        
        // 3. Write to file atomically
        try m3uContent.write(to: toFileURL, atomically: true, encoding: .utf8)
        
        // 4. Handle sidecar image if it exists
        try handleSidecarImage(playlistName: playlistName, fileURL: toFileURL)
    }

    /// Generates .m3u content from an array of SongMetadata
    /// - Parameter songs: Songs to export
    /// - Returns: Formatted .m3u content as String
    private func generateM3UContent(songs: [SongMetadata]) -> String {
        var content = "#EXTM3U\n"
        for song in songs {
            // #EXTINF:-1,Title - Artist\nFilePath\n
            content += "#EXTINF:-1,\(song.title) - \(song.artist)\n\(song.localURL.path)\n"
        }
        return content
    }

    /// Handles sidecar image copying if a PNG with the same name exists
    /// - Parameters:
    ///   - playlistName: Name of the playlist
    ///   - fileURL: URL of the exported .m3u file
    /// - Throws: Error if copy operation fails unexpectedly
    private func handleSidecarImage(playlistName: String, fileURL: URL) throws {
        // Sidecar image path: same directory, same base name with .png extension
        let sidecarURL = fileURL.deletingLastPathComponent().appendingPathComponent("\(playlistName).png")
        if FileManager.default.fileExists(atPath: sidecarURL.path) {
            // Already exists at target location, no action needed
            // In a real implementation, we might copy from a staging area
        }
    }

    // MARK: - Import Workflow
    /// Imports a .m3u file and re-populates the database with matching songs in order
    /// - Parameters:
    ///   - fromFileURL: URL of the .m3u file to import
    ///   - allSongs: Complete array of currently available SongMetadata objects
    /// - Returns: Array of SongMetadata that were successfully matched and reordered
    /// - Throws: Various errors during parsing or database operations
    func importPlaylist(fromFileURL: URL, allSongs: [SongMetadata]) throws -> [SongMetadata] {
        // 1. Read the .m3u file content
        guard let content = try? String(contentsOf: fromFileURL) else {
            throw PlaylistExporterError.fileReadFailed
        }
        
        // 2. Parse lines and extract song metadata
        let lines = content.components(separatedBy: .newlines)
        var matchedSongs: [SongMetadata] = []
        var currentSongMetadata: [String: String] = [:]
        
        // 3. Process each line
        for line in lines {
            if line.hasPrefix("#EXTINF") {
                // Parse metadata from EXTINF line
                let metadata = parseM3ULine(line)
                currentSongMetadata = metadata
            } else if !line.isEmpty && !line.hasPrefix("#") {
                // This is a file path line
                if let song = matchSongByPath(path: line, allSongs: allSongs) {
                    matchedSongs.append(song)
                }
                // Reset current metadata for next entry
                currentSongMetadata = [:]
            }
        }
        
        // 4. Reorder songs in the database
        try reorderPlaylistInDatabase(songs: matchedSongs)
        
        // 5. Return the matched songs array
        return matchedSongs
    }

    /// Parses an #EXTINF line to extract song metadata
    /// - Parameter line: The #EXTINF line from .m3u file
    /// - Returns: Dictionary with title, artist, album, and filePath components
    private func parseM3ULine(_ line: String) -> [String: String] {
        var metadata: [String: String] = [:]
        if line.hasPrefix("#EXTINF") {
            // Split by comma: #EXTINF:duration,Title - Artist
            let parts = line.components(separatedBy: ",")
            if parts.count >= 2 {
                // Extract title and artist from the second part
                let titleArtist = parts[1].trimmingCharacters(in: .whitespaces)
                let components = titleArtist.split(separator: " - ", maxSplit: 1)
                metadata["title"] = components[0]
                metadata["artist"] = components.count > 1 ? String(components[1]) : ""
                // Album is not typically in EXTINF, but could be in extended info
            }
        }
        return metadata
    }

    /// Matches a song in the database by comparing file path
    /// - Parameters:
    ///   - path: File path from .m3u file
    ///   - allSongs: All available songs to match against
    /// - Returns: Matching SongMetadata or throws an error if not found
    /// - Throws: .matchingFailed if no match is found
    private func matchSongByPath(path: String, allSongs: [SongMetadata]) throws -> SongMetadata {
        for song in allSongs {
            // Compare normalized file paths
            if song.localURL.path == path {
                return song
            }
        }
        throw PlaylistExporterError.matchingFailed
    }

    /// Reorders songs in the database to form a new playlist
    /// - Parameter songs: Array of songs to reorder
    /// - Throws: Error if database operations fail
    private func reorderPlaylistInDatabase(songs: [SongMetadata]) throws {
        // Extract song pids from matched songs
        let songPids = songs.map { $0.localURL.path }
        
        // Create a new playlist entry in the database
        // Note: This is a simplified version - actual implementation would need to:
        // 1. Generate a new container_pid
        // 2. Insert into container table
        // 3. Insert container_item entries with sequential positions
        // 4. Handle any playlist-specific metadata
        
        Logger.shared.log("[PlaylistExporter] Would reorder \(songs.count) songs in database")
        // Actual database reordering would be implemented here using MediaLibraryBuilder
    }

    // MARK: - Error Handling
    enum PlaylistExporterError: Error {
        case invalidInput
        case fileReadFailed
        case matchingFailed
        case reorderingFailed
    }
}
